# Site settings
title: "Support Cafe"
description: "Podcaster"
podcast-description: ""
url:  "https://customersupport.cafe" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Ray Bogman"
  email: "hello@raybogman.com"
  url: "https://raybogman.com"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: raybogman
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Ray Bogman
  links:
    - https://github.com/raybogman
    - https://twitter.com/raybogman
    - https://www.linkedin.com/in/raybogman/
lang: it

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Support Cafe
podcast_author: Ray Bogman
podcast_email: hello@raybogman.com
podcast_subtitle: "Podcast"
podcast_summary: "Podcast. This is your podcast's summary."
podcast_description: "Podcast. This is your podcast's description."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2022-04-01" #Launch date of your podcast
podcast_copyright: "&#xA9;Ray Bogman"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"
