name: Jekyll Build + StatiCrypt
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test

    steps:
      - name: Checkout Site
        uses: actions/checkout@v3
      
      - name: Build Site
        uses: ealenn/jekyll-build-action@v1
      - run: sudo apt install nodejs
      - run: sudo npm install -g staticrypt
      - run: sudo touch ${{ github.workspace }}/_site/.staticrypt.json
      - run: sudo chown runneradmin:runneradmin ${{ github.workspace }}/_site/.staticrypt.json
      - run: ls -la _site/
      - run: staticrypt ${{ github.workspace }}/_site/index.html MY_PASSPHRASE -o ${{ github.workspace }}/_site/index.html





