name: StatiCrypt
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          package-manager: npm
          command: npm i staticrypt
          command: staticrypt index.html password123


