name: StatiCrypt
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        uses: ealenn/jekyll-build-action@v1
      - run: ls -la
      - run: pwd
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i staticrypt
      - run: ls -la
      - run: pwd
      - run: npm start




