name: Jekyll Build + StatiCrypt
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Site
        uses: actions/checkout@v3
      
      - name: Build Site
        uses: ealenn/jekyll-build-action@v1
      - run: cat _site/index.html
      - run: pwd
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i staticrypt
      - run: cd _site
      - run: ls -la
      - run: npx staticrypt ${{ github.workspace }}/_site/index.html password123
      - run: cat index.html
      - run: pwd
      - run: npm start



