name: StatiCrypt
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i staticrypt
      - run: staticrypt index.html password123


